name: flutter_healthtrack
description: A Flutter project.

# Version
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # إضافة حزمة intl للـ NumberFormat
  intl: ^0.17.0

  # أيقونات Cupertino
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # هنا ممكن تضيف أي assets مستقبلية
  # assets:
  #   - assets/images/
  assets:
      - lib/assets/images/